In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

### Ans - 1

#### Yes, there is a big difference between list and numpy array.
#### List takes more space then numpy array.

In [20]:
type(list_)

list

In [21]:
type(array_list)

numpy.ndarray

### Ans - 2

In [22]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [23]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Ans - 3

In [24]:
array_list = np.array(object = list_, dtype = int)

In [25]:
array_list

array([1, 2, 3, 4, 5])

In [26]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [28]:
for i in range(len(array_list)):
    print(type(list_[i]),type(array_list[i]))

<class 'str'> <class 'numpy.int32'>
<class 'str'> <class 'numpy.int32'>
<class 'str'> <class 'numpy.int32'>
<class 'str'> <class 'numpy.int32'>
<class 'str'> <class 'numpy.int32'>


### Ans - 4

In [30]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [31]:
num_array.shape

(2, 3)

In [32]:
num_array.size

6

### Ans - 5

In [33]:
arr = np.zeros(shape=(3,3)) np.NaN

In [34]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Ans - 6

In [35]:
arr2 = np.eye(5)

In [36]:
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])